### ISSUE TITLE
vROAST 0.7.3 Unable to import content from embedded vRO

### ISSUE THREAD

**Issue by kskilling** [orangeglasses/vROAST#10]
vROAST 0.7.3 failing to import content from embedded vRO 7.5 instance. Log file on vROAST shows 

> Pulling git repo.
> [09:56:05] [INF] [14] [MedKit.Jobs.JobExecuter] Done pulling repo. Now get vRO content.
> [09:56:05] [INF] [14] [MedKit.Jobs.JobExecuter] Clearing vro cache folder: /tmp/vroast/work/vroCache/<vRO hostname>/pullfromvro
> [09:56:05] [INF] [14] [MedKit.Jobs.JobExecuter] Now getting vRO content from: https://<vRO hostname>:443
> [09:56:06] [ERR] [14] [MedKit.vRO.vROClient] Failed to download TS definition file

It then tries port 8281 and get connection refused as expected. <vRO hostname> is actually the vRO FQDN in the log file, I've removed it for security reasons.
I'm using administrator@vsphere.local as the username, confirmed correct credentials by removing @vsphere.local and observing invalid username error in logs on vRO.  vRO has self signed untrusted certificate in case that makes a difference.

**Comment by floreseken** [comment]
vROAST accepts all certificates, that can not be the issue..

I guess what's going wrong here is that the vROAST appliance tries to download the TS definition files from https://www.vroapi.com and fails to do so..
I would expect the next log line (that is not included above) to complain about this..

Does the vROAST appliance has internet access?

**Comment by floreseken** [comment]
btw, we know this is a requirement that we should get rid of in the final version, we have some ideas this this.

**Comment by kskilling** [comment]
vROAST has internet access. I can resolve vroapi.com using nslookup and perform a curl to it which returns the text from the homepage with the list of plugins.

I can't see the line you are expecting in the log file but I will email you a copy of the log file so you can check for more information.

**Comment by floreseken** [comment]
Yes please, feken@itq.nl

**Comment by floreseken** [comment]
So, I'm testing this with a standalone vRO (because the integreated is more hassel to setup) and based on your log file I suspect that the portnumber is not the only difference.

Could you please tell me what you see when you try to browse to:

https://[embedded vro]:443/vco/api

Thanks.

**Comment by kskilling** [comment]
I get an XML page with api information. Here's the start of the page it returns

`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<service-descriptors xmlns="http://www.vmware.com/vco">
<service href="https://<vro hostname>/vco/api/server/">
<description>vCO Server instance Service API.</description>
</service>
<service href="https://<vro hostname>/vco/api/about">
<description>
Returns server build info, like build date and build number.
</description>
</service>`

**Comment by floreseken** [comment]
Okay that sounds good.

Upon further investigation It appears that adding the retry on the different vRO api ports has introduced a 'bug' that now is hiding crucial exception information about what goes wrong later on..

I'm fixing this right now..

**Comment by floreseken** [comment]
There is now a new release available, this has added logging the diagnose your connection problems. Could you please try it with this new release?

Thanks

**Comment by kskilling** [comment]
Of course, I will start the download now. I should be able to get it setup in my lab at lunchtime (UK time) to provide results/updated log file for you.

**Comment by kskilling** [comment]
new version deployed, import is still failing but there is now a message in the log "Failure getting vRO content
MedKit.Exceptions.TsDownloadException: Unable to download defintion file: TeamFoundationServer version: 7.5.0-SNAPSHOT. Make sure the plugin with this version exists on vroapi.com and that the engine can access it"

I will email across the plugin file so it can be added to the site.

**Comment by floreseken** [comment]
Aha.. thanks to improved logging..
That's makes a lot more sense

Unfortunately your email attachment got blocked. Could you try wetransfer.com or host the file elsewhere?

**Comment by kskilling** [comment]
Stupid email system. I've sent you a link via email to download the file.

**Comment by floreseken** [comment]
Okay, that worked. I will try to get it online today.

**Comment by ruurdk** [comment]
It's online

**Comment by kskilling** [comment]
Thanks, it's now complaining about another missing plugin. I'll check each of the configured plugins I have across my labs and send across details of any missing ones so they can be uploaded in one job. In the meantime I'll try and find an appliance without the extra plugins to test it on.

**Comment by ruurdk** [comment]
Thanks for your persistence. I just opened an issue to change the fail on missing metadata behavior.

**Comment by kskilling** [comment]
I've sent a link to Flores with the plugin files I think are missing based on my 7.5 appliance. I'm trying to get the same details for the 7.4 appliance I have in another environment and will share those files once I have them.

**Comment by floreseken** [comment]
I'll go ahead and close this issue, since the initial problem is solved.
