### ISSUE TITLE
on vRO servers with a lot of content the recurring job will execute concurrently, causing a lot of confusing exceptions

### ISSUE THREAD

**Issue by floreseken** [orangeglasses/vROAST#13]
Drawing this conclusion based on a log file from @kskilling

Needs more investigation

**Comment by floreseken** [comment]
We are depending on a feature from hangfire to prevent concurrent execution.. which seems to be not that uncontroversial: https://github.com/HangfireIO/Hangfire/issues/1053

**Comment by floreseken** [comment]
Setting the workercount to 1 should bring a solution:

https://stackoverflow.com/questions/44447660/hangfire-disableconcurrentexecution-vs-worker-count-1

Need to test this..

**Comment by floreseken** [comment]
Problem is solved in our test version, and will be in the next release.

**Comment by floreseken** [comment]
The new release (0.7.5) is available now, could you try with that one?

**Comment by kskilling** [comment]
Early results are looking good. I can see content in the Git repo from vROAST now. I haven't had a chance to check the logs to make sure everything is working but the original issue is resolved, I'll log a new one if I find anything unexpected in the logs later. Thanks for the help 👍

**Comment by floreseken** [comment]
Great! I'll close this for now.
