### ISSUE TITLE
Unable to logon to the appliance with the given password in install instructions

### ISSUE THREAD

**Issue by CptLolliPants** [orangeglasses/vROAST#14]

**Comment by floreseken** [comment]
The user name is also case-sensitive, so: Admin 
could that be your problem?

**Comment by CptLolliPants** [comment]
Concerns these credentials: vroast/Hey^#&T3663

**Comment by floreseken** [comment]
Ha, right. using SSH or directly on the console? using SSH might be disabled by default (not sure)

**Comment by CptLolliPants** [comment]
on the console, we don't use DHCP so trying to logon using SSH was not even an option

**Comment by kskilling** [comment]
Credentials work for me on v0.7.4 accessing via console window in vCenter (and via SSH which is enabled by default). Username vroast all lower case, password as printed on website Hey^#&T3663

**Comment by floreseken** [comment]
Just downloaded the current ova and deployed it, I'm able to logon with the given credentials. I'm closing this as not reproducible.

**Comment by CptLolliPants** [comment]
Confirmed login in the console. vSphere Web Console has problems with echoing characters. Wortks with Remove Console.
