### ISSUE TITLE
Jobs failing with Connection Refused and push to vRO not working

### ISSUE THREAD

**Issue by kskilling** [orangeglasses/vROAST#19]
v0.7.8 all jobs failing with a connection refused error, including initial sync. Content populated in git repo is not being pushed to vRO either with the same error message.

Initial sync job has copied across content to the repo, and it looks as though all actions from vRO inventory have been pushed to the repo but the job shows as failed in vROAST.

Created a new action via VSCode and pushed to the git repo successfully. vROAST log shows it picking up the new commit on the repo but job to sync the content fails and the action does not appear in vRO inventory.
Log file will be provided via email.

**Comment by floreseken** [comment]
Okay. I'm investigating this.. and i'm fairly sure it is related to #7 
Looks like the fallback works correctly when getting content, but not when sending content.
This is hard to test for me because I'm running the standalone version.

Will fix this today, I appreciate your persistence Katherine!

**Comment by floreseken** [comment]
Okay. This is fixed in https://github.com/orangeglasses/vROAST/releases/tag/0.7.9.

Please try again

**Comment by floreseken** [comment]
This appears to still be a problem..

**Comment by floreseken** [comment]
So, this auto-port-detection remains a problem till today. I've decided we will make a breaking change and the port must be provided in the config. That should solve it once and for all.

**Comment by floreseken** [comment]
So, this should finally be solved now with this release: https://github.com/orangeglasses/vROAST/releases/tag/0.8.0
