### ISSUE TITLE
Failure during jobexecution: Action -> TS...

### ISSUE THREAD

**Issue by codevieillard** [orangeglasses/vROAST#2]
**Environment:**
OS = Win10
vRO runs in VMware Workstation
vROAST in docker on VirtualBox (`$ docker-machine create --driver=virtualbox vbox-test`)

**Scenario:**
After I download, fill in template.yml and run `$ Bandaid set-jobs -c template.yml` I get this error:

> Error! Could not find a part of the path
> '/tmp/thedoctor/work/vroCache/192.168.200.206/pullfromvro/action'

From UI:
![image](https://user-images.githubusercontent.com/47833049/53202995-38243700-3628-11e9-9871-6bcc573b5d89.png)

After login to the container running `ls` in _/tmp/thedoctor/work/vroCache/192.168.200.206/pullfromvro/_ it seems folders are created weirdly:
![image](https://user-images.githubusercontent.com/47833049/53202678-6b19fb00-3627-11e9-9121-cde38665a287.png)

**Comment by floreseken** [comment]
In an attempt to reproduce this I'm now running my vROAST docker image via docker-machine on VMware workstation (and vRO itself also).
But that works fine.. have you also tried to run the docker image in VMware workstation?

I did find some suspicious code that might cause this, I'm in the process of rewriting and testing that.

**Comment by floreseken** [comment]
Okay. Suspicious code is removed, and all seems fine. I'm sending you a new docker image in a minute.

**Comment by codevieillard** [comment]
Thanks - I tried the new docker image. Got it working now!

As reply on your question; I did try to run vROast in VMware Workstation (`$ docker-machine create --driver=vmwareworkstation dev`) with the old image. That gave the same result.

**Comment by floreseken** [comment]
Cool
