### ISSUE TITLE
TypeDefinition intrinsics wrongly parsed

### ISSUE THREAD

**Issue by codevieillard** [orangeglasses/vROAST#3]
While reading trough the code I noticed in the intrinsic TD, specifically the interface WorkflowToken is broken:

![image](https://user-images.githubusercontent.com/47833049/53332151-e9f68880-38f2-11e9-90ec-61a76a058e40.png)

Guess it should be `readonly attributesStack: Attribute[];`

**Comment by floreseken** [comment]
This caused by vROAST levering the definitions of vroapi.com, in which it is also wrong:

![image](https://user-images.githubusercontent.com/6927344/53334307-aacb3600-38f8-11e9-87b4-c2fff97db520.png)

Working on a fix..

**Comment by floreseken** [comment]
This is fixed now in vroapi.com. But the definition file is cached, so this won't be fixed automatically in your repo. 

Workaround for now is to manually fix this in your current repo. It won't happen in the next you configure.

**Comment by codevieillard** [comment]
That was quick! Thanks for the explanation. I fixed it as you suggested
