### ISSUE TITLE
vroapi lookup for -SNAPSHOT in plugin name

### ISSUE THREAD

**Issue by piwi3910** [orangeglasses/vROAST#30]
when creating the connection, VROAST is looking for https://www.vroapi.com/Plugin/TeamFoundationServer/7.5.0-SNAPSHOT
however, all the codestream plugins are on vroapi as ->
https://www.vroapi.com/Plugin/TeamFoundationServer/7.5.0

**Comment by ruurdk** [comment]
Thanks for reporting. We made a large update on vroapi - including dropping the "-SNAPSHOT" from plugin versions. Apparently this broke vROast...

**Comment by floreseken** [comment]
This should be fixed in the new release: https://github.com/orangeglasses/vROAST/releases/tag/0.8.1
