### ISSUE TITLE
Appliance supports DHCP networking only in 0.7.1

### ISSUE THREAD

**Issue by vOlliestrator** [orangeglasses/vROAST#6]
The vROAST appliance only supports the use of DHCP for networking. Could you please add an option to setup a static IP address?

**Comment by floreseken** [comment]
Since the appliance is just a regular Ubuntu 18.04 you should be able to fix that with this manual: https://linuxconfig.org/how-to-configure-static-ip-address-on-ubuntu-18-04-bionic-beaver-linux 

You can find the user and password of the appliance here: https://www.vroast.io/install/

**Comment by floreseken** [comment]
I'll go ahead and close this issue, because I don't expect work from our side.
