### ISSUE TITLE
vRO embedded in vRA

### ISSUE THREAD

**Issue by darophill** [orangeglasses/vROAST#7]
When vRO is embedded in vRA the port used is 443 not 8281. Is there a way to specify the port to use with an embedded vRO?

**Comment by floreseken** [comment]
I've worked with embedded vRO's before and I would say they use the same portnumber, but I might be mistaken.. just to be sure, in this client:

![image](https://user-images.githubusercontent.com/6927344/54877471-aaeb2280-4e1f-11e9-9707-32fc81c8de6b.png)

You also are using 443?

We need to make the port number configurable in that case..

**Comment by AndreasDiemer** [comment]
Stand alone vRO uses port 8281, vRA embeded vRO is presented via 443 (internal proxy) for fat client and ReST API.

**Comment by floreseken** [comment]
Related: https://github.com/orangeglasses/vROAST/issues/8

**Comment by floreseken** [comment]
The new version will default to port 443, and if that fails will try 8281.

**Comment by floreseken** [comment]
The fix is now available in this release: https://github.com/orangeglasses/vROAST/releases/tag/0.7.3
