### ISSUE TITLE
Cannot import content from vRO

### ISSUE THREAD

**Issue by maciek01170** [orangeglasses/vROAST#8]
Hello, 

Thank you for this tool, really great idea. I spent more than one year on developing vRO stuff and this is precisely what I always needed :)

Unfortunately, I am unable to get the content from the vRO embedded within vRA using vRoast 0.7.2. 

My vroast.yml is below, the message I log in job dashboard says "Failure during jobexecution" (job output below) just when trying to get the vRO content ... so, there is an issue when connecting to vRO. The credentials provided in vroast.yml are the same as those used when logging to vro... I would suspect two things : 
1. the vRO has no valid https certificate?
2. auth type is possibly wrong?

Thank you very much for your help.

Otherwise I would have another question: what are the appliance (.ova) and the docker image doing? Can I run only one of them? I noticed that the web pages on localhost -> with docker and IP like 172.16... -> ova appliance are very similar but seem to run different jobs depending on the setting of vRoast target --url ... 

Looking forward to hearing from you!

Best Regards - 

Maciej Macowicz, EPFL - Swiss Federal Institute of Technology, Lausanne, Switzerland.

vroast.yml:
***********
--
syncjobs:
  - name: myfirstpush
    mode: pushtovRO
    vro:
      host: vsissp-vra-test.epfl.ch
      auth:
        type: basic
        username: ***
        password: ***
    scc:
      url: https://c4science.ch/diffusion/VRO/vro.git
      branch: master
      auth:
        type: basic
        username: ***
        password: ***
        email: Maciej.Macowicz@epfl.ch

Job output :
************
+30msWe are in the job executer
+35msStarting with myfirstpush [pushtovro]
+40mspluginRepoPath: /tmp/vroast/pluginRepo
+43msWorking src path: /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pushtovro
+45msThis is a pull from GIT and push to vRO job. Using host: vsissp-vra-test.epfl.ch
+49msSetting up sourcecontrol. Pulling remote: https://c4science.ch/diffusion/VRO/vro.git to /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pushtovro
+52msLocal working folder path: /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pushtovro. Pulling git repo.
+1.249sDone pulling repo. Checking contents..
+1.252sThe pulled repo apears to be empty. For convenience a pull job will be triggered now
+1.254s    Working src path: /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pullfromvro
+1.256s    This is a pull from VRO and push to GIT job. Using vRO host: vsissp-vra-test.epfl.ch
+1.258s    Setting up sourcecontrol. Pulling remote: https://c4science.ch/diffusion/VRO/vro.git to /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pullfromvro
+1.260s    Local working folder path: /tmp/vroast/work/srcCache/https:--c4science.ch-diffusion-VRO-vro.git/master/pullfromvro. Pulling git repo.
+2.447s    Done pulling repo. Now get vRO content.
+2.450s    Clearing vro cache folder: /tmp/vroast/work/vroCache/vsissp-vra-test.epfl.ch/pullfromvro
+2.452s    Now getting vRO content
+10.468sFailure during jobexecution
+10.471sError! Connection refused Connection refused
+10.472sInner exception: Connection refused
+10.474sStacktrace:    at System.Net.HttpWebRequest.GetResponse()
   at System.Net.WebClient.GetWebResponse(WebRequest request)
   at System.Net.WebClient.DownloadBits(WebRequest request, Stream writeStream)
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at MedKit.vRO.vROClient.GetContent(String type) in /app/Common/vRO/vROClient.cs:line 116
   at MedKit.vRO.vROClient.GetAllContent() in /app/Common/vRO/vROClient.cs:line 190
   at MedKit.Jobs.JobExecuter.executePullFromVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 166
   at MedKit.Jobs.JobExecuter.executePushToVroJob(Job job, CombinedLogger comboLogger) in /app/Common/Jobs/JobExecuter.cs:line 81
   at MedKit.Jobs.JobExecuter.Execute(Job job, PerformContext context) in /app/Common/Jobs/JobExecuter.cs:line 41

**Comment by floreseken** [comment]
This might be related to this problem: https://github.com/orangeglasses/vROAST/issues/7

If you connect with the vRO client, which port are you using?

**Comment by maciek01170** [comment]
443. So waiting for the enhancement to be done :)
Thank you!

**Comment by floreseken** [comment]
Yes! Will do that.. We will also improve the logging here to include the url that we are using to connect.. so there is less guessing what is going on..

**Comment by floreseken** [comment]
The enhancement is on it's way..

**Comment by floreseken** [comment]
The new version will default to port 443, and if that fails will try 8281.

**Comment by floreseken** [comment]
The fix is now available in this release: https://github.com/orangeglasses/vROAST/releases/tag/0.7.3
